### ISSUE TITLE
Cannot sign Permit2 to simulate Uniswap transactions

### ISSUE THREAD

**Issue by zarifpour** [DarkFlorist/TheInterceptor#780] opened 2023-11-22 16:50 UTC
Just installed v0.0.73 and I'm failing to transact with Uniswap. Previously, in v0.0.72 I believe it was possible.

![CleanShot 2023-11-22 at 11 49 04 on Google Chrome — Personal Sign - The Interceptor@2x](https://github.com/DarkFlorist/TheInterceptor/assets/16494335/9183eeef-1bbc-4108-aa9f-66e4a6a18f39)

**Comment by KillariDev** [comment] 2023-11-22 19:07
<img width="222" alt="image" src="https://github.com/DarkFlorist/TheInterceptor/assets/13102010/e757ec26-c4c2-4ebf-af04-507e7c993bcb">
If you change here to experimental geth client, you should be able to sign it. But yeah, that should also Work. I'll look what's wrong with it

**Comment by KillariDev** [comment] 2023-11-28 15:59
This is duplicate of https://github.com/DarkFlorist/TheInterceptor/issues/760

Unfortunately Uniswap decided to develop Uniswap V4 which makes their exchange to require centralized components so we are unable to simulate this kind of messages to make the swap to work :/

**Closed by KillariDev** 2023-11-28 15:59 UTC
Labels: bug
